### PR TITLE
Add py.typed

### PR DESCRIPTION
**Pull request by mmaslowskicc**
This allows mypy to use the present type annotations in packages using an installed prometheus-fastapi-instrumentator.

### CODE REVIEW

**Comment by Kludex** [comment]
I think you also need to add `include = ["{{ cookiecutter.package }}/py.typed"]` in the pyproject :thinking:

**Comment by mmaslowskicc** [comment]
It was included in the built sdist and wheel, but I'm not sure how Poetry determines what to include by default, so I added the `include`. Thanks.

**Comment by trallnag** [comment]
Thanks

**Comment by trallnag** [comment]
According to this blogpost adding the file in pyproject.toml is not necessary https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Pull request merged**
