### PR TITLE
feat: Add request body to info.response object

### PR DESCRIPTION
**Pull request by HadilD**

### CODE REVIEW

**Comment by msemelman-vrff** [comment]
comment to link to issue:

fixes 76

**Comment by msemelman-vrff** [comment]
Trying to link the issue to PR:
Fixes #76

**Review by roger-domenech-aguilera — APPROVED** [review]

**Comment by trallnag** [comment]
Thanks

**Comment by trallnag** [comment]
There is a bug with this implementation. See issue #236.

It only works if response data is being streamed.

**Comment by trallnag** [comment]
FYI: There is a new release with a breaking change regarding this feature.

https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/v6.0.0

**Comment by HadilD** [comment]
Great, thanks!

Sorry about the bug.

**Pull request merged**
