### PR TITLE
feat: Add support for async instrumentation functions

### PR DESCRIPTION
**Pull request by AndreasPB**

### CODE REVIEW

**Review by s3rius — APPROVED** [review]

**Comment by caspervk** [comment]
@trallnag should this be merged?

**Comment by Skeen** [comment]
Async support would be great

**Comment by AndreasPB** [comment]
We still need this change at work, so it would be awesome to have it on master :)

**Comment by Skeen** [comment]
> ... Can you add examples on how you use `async_instrumentation`?

Hi, we use this feature actively.

The use-case is exactly as with the non-async case:
```python
sync_metric = Info("sync_metric", "Documentation")
async_metric = Info("async_metric", "Documentation")

def sync_function(_: InstInfo) -> None:
    value = sync_metric_getter()
    sync_metric.info({"type": value})

async def async_function(_: InstInfo) -> None:
    value = await async_metric_getter()
    async_metric.info({"type": value})

instrumentator = Instrumentator()

instrumentator.add(sync_function)
instrumentator.add(async_function)
```

**Comment by trallnag** [comment]
@Skeen, thanks for the example. Adapted it into a unit test

**Comment by Skeen** [comment]
> @Skeen, thanks for the example. Adapted it into a unit test

You're awesome, thank you for the work that you do!

**Comment by AndreasPB** [comment]
What @Skeen said - Thank you!

One last request, would it be possible to get a release with these changes sometime in the near future, @trallnag?

**Comment by trallnag** [comment]
@AndreasPB, I'll release it already this weekend

**Pull request merged**
